<a href="https://colab.research.google.com/github/MiscMissLA/Mini-Project-01-Python-Assignment/blob/main/Assignment_Basics_Of_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
L = [11,12,13,14]
L.append(50)
L.append(60)
print(L)
print("----")


if (11 in L) == True:
  try:
    del L[0]
  except:
    print("Not Present.")
else:
  print("Not Present.")

if (13 in L) == True:
  try:
    del L[1]
  except:
    print("Not Present.")
else:
  print("Not Present.")
print(L)
print("----")


L.sort()
print(L)
print("----")


L.sort(reverse = True)
print(L)
print("----")


if (13 in L) == True:
  print("Present.")
else:
  print("Not Present.")
print("----")


for i in L:
  print(i, " count:  ", L.count(i))
print("----")


sum = 0
for i in L:
  sum+=i
print("sum is: ", sum)
print("----")


sum_odd = 0
sum_even = 0
for i in L:
  if (i%2!=0):
    sum_odd+=i
  else:
    sum_even += i
print("sum of odd numbers: ", sum_odd)
print("----")


print("sum of even numbers: ", sum_even)
print("----")


import math as m
flag = 0
sum_prime = 0
for i in L:
  for j in range(2, int(m.sqrt(i))+1):
    if (i%j == 0):
        print("Not Prime")
        flag = 1
        break
  if (flag == 0):
    sum_prime += i
    print("Prime ", i)
print("sum of prime numbers in list: ", sum_prime)
print("----")


L.clear()
print(L)
print("----")


del L
try:
  print(L)
except:
  print("Deleted.")
print("----")

[11, 12, 13, 14, 50, 60]
----
[12, 14, 50, 60]
----
[12, 14, 50, 60]
----
[60, 50, 14, 12]
----
Not Present.
----
60  count:   1
50  count:   1
14  count:   1
12  count:   1
----
sum is:  136
----
sum of odd numbers:  0
----
sum of even numbers:  136
----
Not Prime
Not Prime
Not Prime
Not Prime
sum of prime numbers in list:  0
----
[]
----
Deleted.
----

In [4]:
D = {1:5.6, 2:7.8, 3:6.6, 4:8.7, 5:7.7}

D[8] = 8.8
print(D)
print("----")


del D[2]
print(D)
print("----")


if (6 in D) == True:
  print("Present.")
else:
  print("Not Present.")
print("----")


count = 0
for i in D:
  count+=1
print("Count : ",count)

print("Count : ", len(D))
print("Count : ", len(D.keys()))
print("Count : ", len(D.values()))
print("----")

sum_values = 0
for i in D:
  sum_values += D[i]
print("Sum of values is: ", sum_values)
print("----")

if (3 in D):
  D[3] = 7.1
else:
  print("Not Present.")
print(D)
print("----")


D.clear()
print(D)
print("----")

del D
try:
  print(D)
except:
  print("Deleted.")
print("----")

{1: 5.6, 2: 7.8, 3: 6.6, 4: 8.7, 5: 7.7, 8: 8.8}
----
{1: 5.6, 3: 6.6, 4: 8.7, 5: 7.7, 8: 8.8}
----
Not Present.
----
Count :  5
Count :  5
Count :  5
Count :  5
----
Sum of values is:  37.4
----
{1: 5.6, 3: 7.1, 4: 8.7, 5: 7.7, 8: 8.8}
----
{}
----
Deleted.
----

In [5]:
S1 = {10, 20, 30, 40, 50, 60}
S2 = {40, 50, 60, 70, 80, 90}

print(S1)
print(S2)
print("----")

S1.add(55)
S1.add(66)
print(S1)
print("----")

S1.remove(10)
S1.remove(30)
print(S1)
print("----")

if (40 in S1):
  print("40 is Present.")
else:
  print("40 is Not Present.")
print("----")

print("Union of S1 and S2: ", S1.union(S2))
print("----")

print("Intersection of S1 and S2: ", S1.intersection(S2))
print("----")

print("Difference of S1 and S2: ", S1-S2, S1.difference(S2), " Symmetric Difference: ", S1.symmetric_difference(S2))
print("----")

{50, 20, 40, 10, 60, 30}
{80, 50, 70, 40, 90, 60}
----
{50, 66, 20, 55, 40, 10, 60, 30}
----
{50, 66, 20, 55, 40, 60}
----
40 is Present.
----
Union of S1 and S2:  {66, 70, 40, 80, 50, 20, 55, 90, 60}
----
Intersection of S1 and S2:  {40, 50, 60}
----
Difference of S1 and S2:  {66, 20, 55} {66, 20, 55}  Symmetric Difference:  {80, 66, 20, 70, 55, 90}
----

In [6]:
import string as s
import random as r
import math as m

for i in range(1,101):
  rs = r.sample(s.ascii_letters+s.digits+"!@#$%^&*", r.randint(6,8))
  rs = "".join(rs)
  print(i, rs)
print("----")


for i in range(600, 801):
  flag = 0
  for j in range(2, int(m.sqrt(i))+1):
    if (i%j == 0):
      flag = 1
      break
  if flag == 0:
    print(i , " is prime. ")
print("----")


for i in range(100, 1001):
  if (i%7 == 0 and i%9 == 0):
    print(i, "is divisible by 7 and 9.")
print("----")

1 ^c*pEt
2 zPcugv9
3 jv@ycbZB
4 %Dg@eY
5 O0Gu8XTs
6 $AhTlS0E
7 eAKgd7X
8 H4LgA8T
9 B2KHGLV
10 zdjP5^p$
11 KR2C1#TJ
12 7BQEzu4F
13 cdWoSt
14 BPYEI%
15 wljage
16 Q%ol1nL
17 N1AwIH
18 ^*rf!8h
19 9cZ0zka*
20 DPHimX
21 Ebl28R
22 %G86AbI
23 NPvXgeQ!
24 &nJAz%5Z
25 v*dYWo
26 d$Nm8U3
27 xsm#ek
28 yYbK!UI
29 mk0Nsrq#
30 vP8B2AIs
31 atqR@I*
32 a^*Zg%
33 QpBXq3
34 ^y9hL5*
35 s3rKDu1A
36 QC^bUI
37 &8ZoqEP9
38 OJhtsG@
39 M2dl86
40 JFvQma
41 orKFaS^
42 cCoILZ
43 zhQL&Hj
44 hcMK^l#J
45 WG!QCw
46 Qgak7D^
47 KLyxFNsA
48 Qd6!G%kB
49 VMvzZj
50 XF69lfTt
51 Wv6dq1
52 3V^TY68s
53 yzs$YK53
54 TqvkMGz7
55 SfhbLN!
56 7dBz%Nv
57 Oygnp5
58 ehfYFd2
59 mAIfwM
60 tfByniz
61 siEQ%q
62 Owa%bW
63 Nf@BIp
64 m6tgsIQ
65 fPQ@Bp3
66 eG0#Dl
67 aC68b2VN
68 rgQ1su
69 v9FTUR
70 #BDi^7T
71 Du#xhA0
72 0wMOib9
73 Hz!#X*
74 BfE^CbeO
75 RF2tINug
76 xd#wLSG
77 SKTRQgI&
78 m&pbxv9
79 dDeaCRs6
80 mqvi2Z
81 0iVhB5v
82 V76B@I
83 o41Xdx
84 pnGHj1vs
85 JihQtl
86 DNYkyGCr
87 e#UNLK
88 Z6mgeOlP
89 hGZPjJ
90 5zdbuYZy
91 L$GI!9^A
92 lhBt8Xb
93 m0!DHiL
94 wjD#&i
95 5jI6d2
96 M6%@3wz
97 oQ8wqkT%
98 eP*z$yQH
99 DZ$*wO@a
100 U1^k4R
----
601  is prime.
607  is prime.
613  is prime.
617  is prime.
619  is prime.
631  is prime.
641  is prime.
643  is prime.
647  is prime.
653  is prime.
659  is prime.
661  is prime.
673  is prime.
677  is prime.
683  is prime.
691  is prime.
701  is prime.
709  is prime.
719  is prime.
727  is prime.
733  is prime.
739  is prime.
743  is prime.
751  is prime.
757  is prime.
761  is prime.
769  is prime.
773  is prime.
787  is prime.
797  is prime.
----
126 is divisible by 7 and 9.
189 is divisible by 7 and 9.
252 is divisible by 7 and 9.
315 is divisible by 7 and 9.
378 is divisible by 7 and 9.
441 is divisible by 7 and 9.
504 is divisible by 7 and 9.
567 is divisible by 7 and 9.
630 is divisible by 7 and 9.
693 is divisible by 7 and 9.
756 is divisible by 7 and 9.
819 is divisible by 7 and 9.
882 is divisible by 7 and 9.
945 is divisible by 7 and 9.
----

In [1]:
import random as r
L1 = []
L2 = []

print(L1)
print(L2)
print("----")

for i in range(1, 11):
  L1.append(r.randint(10,30))
  L2.append(r.randint(10,30))

print(L1)
print(L2)
print("----")

for i in L1:
  if i in L2:
    print(i, "is common in both L1 and L2.")
print("----")

L = []
for i in L1:
  if i not in L:
    L.append(i)
print("Unique elements in L1", L)

L.clear()

for i in L2:
  if i not in L:
    L.append(i)
print("Unique elements in L2", L)

L = set(L1)
print(L)

L = set(L2)
print(L)
print("----")

print("Minimum of L1", min(L1))
print("Minimum of L2", min(L2))
print("----")

print("Maximum of L1", max(L1))
print("Maximum of L2", max(L2))
print("----")

print("sum of L1", sum(L1))
print("sum of L2", sum(L2))
print("----")

[]
[]
----
[16, 15, 10, 22, 30, 20, 28, 11, 16, 23]
[13, 25, 11, 14, 18, 11, 18, 26, 15, 12]
----
15 is common in both L1 and L2.
11 is common in both L1 and L2.
----
Unique elements in L1 [16, 15, 10, 22, 30, 20, 28, 11, 23]
Unique elements in L2 [13, 25, 11, 14, 18, 26, 15, 12]
{10, 11, 15, 16, 20, 22, 23, 28, 30}
{11, 12, 13, 14, 15, 18, 25, 26}
----
Minimum of L1 10
Minimum of L2 11
----
Maximum of L1 30
Maximum of L2 26
----
sum of L1 191
sum of L2 163
----

In [2]:
import random as r
import math as m
L = []
for i in range(1,101):
  L.append(r.randint(100,900))

count_odd = 0
count_even = 0
count_prime = 0

for i in L:
  flag = 0
  if i%2 == 0:
    count_even += 1
    print(i, "is even.")
  else:
    count_odd += 1
    print(i, "is odd.")

  for j in range(2, int(m.sqrt(i))+1):
    if i%j == 0:
      flag = 1
      break

  if flag == 0:
    print(i, "is prime.")
    count_prime += 1
  else:
    print(i, "is not prime.")

print("odd count: ", count_odd)
print("even count: ", count_even)
print("prime count: ", count_prime)

229 is odd.
229 is prime.
232 is even.
232 is not prime.
719 is odd.
719 is prime.
126 is even.
126 is not prime.
369 is odd.
369 is not prime.
259 is odd.
259 is not prime.
336 is even.
336 is not prime.
489 is odd.
489 is not prime.
395 is odd.
395 is not prime.
148 is even.
148 is not prime.
352 is even.
352 is not prime.
756 is even.
756 is not prime.
687 is odd.
687 is not prime.
400 is even.
400 is not prime.
388 is even.
388 is not prime.
812 is even.
812 is not prime.
196 is even.
196 is not prime.
384 is even.
384 is not prime.
539 is odd.
539 is not prime.
545 is odd.
545 is not prime.
658 is even.
658 is not prime.
268 is even.
268 is not prime.
664 is even.
664 is not prime.
372 is even.
372 is not prime.
268 is even.
268 is not prime.
380 is even.
380 is not prime.
462 is even.
462 is not prime.
814 is even.
814 is not prime.
311 is odd.
311 is prime.
716 is even.
716 is not prime.
668 is even.
668 is not prime.
428 is even.
428 is not prime.
542 is even.
542 is not prime.
466 is even.
466 is not prime.
885 is odd.
885 is not prime.
750 is even.
750 is not prime.
665 is odd.
665 is not prime.
258 is even.
258 is not prime.
600 is even.
600 is not prime.
602 is even.
602 is not prime.
390 is even.
390 is not prime.
408 is even.
408 is not prime.
863 is odd.
863 is prime.
108 is even.
108 is not prime.
322 is even.
322 is not prime.
856 is even.
856 is not prime.
389 is odd.
389 is prime.
500 is even.
500 is not prime.
402 is even.
402 is not prime.
391 is odd.
391 is not prime.
720 is even.
720 is not prime.
215 is odd.
215 is not prime.
362 is even.
362 is not prime.
217 is odd.
217 is not prime.
331 is odd.
331 is prime.
899 is odd.
899 is not prime.
352 is even.
352 is not prime.
663 is odd.
663 is not prime.
326 is even.
326 is not prime.
573 is odd.
573 is not prime.
149 is odd.
149 is prime.
246 is even.
246 is not prime.
645 is odd.
645 is not prime.
609 is odd.
609 is not prime.
873 is odd.
873 is not prime.
175 is odd.
175 is not prime.
239 is odd.
239 is prime.
242 is even.
242 is not prime.
531 is odd.
531 is not prime.
176 is even.
176 is not prime.
553 is odd.
553 is not prime.
537 is odd.
537 is not prime.
539 is odd.
539 is not prime.
550 is even.
550 is not prime.
694 is even.
694 is not prime.
213 is odd.
213 is not prime.
298 is even.
298 is not prime.
375 is odd.
375 is not prime.
777 is odd.
777 is not prime.
651 is odd.
651 is not prime.
545 is odd.
545 is not prime.
224 is even.
224 is not prime.
332 is even.
332 is not prime.
692 is even.
692 is not prime.
661 is odd.
661 is prime.
292 is even.
292 is not prime.
540 is even.
540 is not prime.
889 is odd.
889 is not prime.
357 is odd.
357 is not prime.
448 is even.
448 is not prime.
452 is even.
452 is not prime.
575 is odd.
575 is not prime.
167 is odd.
167 is prime.
867 is odd.
867 is not prime.
881 is odd.
881 is prime.
532 is even.
532 is not prime.
353 is odd.
353 is prime.
684 is even.
684 is not prime.
142 is even.
142 is not prime.
777 is odd.
777 is not prime.
odd count:  45
even count:  55
prime count:  12

In [7]:
D = {1:"One", 2: "Two", 3: "Three", 4:"Four", 5:"Five"}
fp = open("file1.txt", "w")
for i in D:
  fp.write(str(i)+","+str(D[i])+"\n")
fp.close()

In [8]:
L = ["One", "Two", "Three", "Four", "Five"]
fp = open("file1.txt", "w")
for i in L:
  fp.write(i+","+str(len(i))+"\n")
fp.close()

In [9]:
import string as s
import random as r

fp = open("file1.txt", "w")

for i in range(1, 101):
  rs = r.sample(s.ascii_letters, r.randint(10,15))
  rs = "".join(rs)
  fp.write(rs+"\n")

fp.close()

In [10]:
import math as m
fp = open("file1.txt", "w")
for i in range(600, 801):
  flag = 0
  for j in range(2, int(m.sqrt(i))+1):
    if (i%j == 0):
      flag = 1
      break
  if flag == 0:
    fp.write(str(i)+"\n")

fp.close()

In [17]:
n = int(input("Enter the number of students: "))
D = {}
for i in range(0, n):
  name = input("Enter the name of the student: ")
  sum = 0
  for j in range(0,5):
    s = "Enter the marks of the student in subject %d: " %(j+1)
    marks = int(input(s))
    sum += marks
  avg = sum/5;
  D[name] = avg
print(D)

for i in D:
  if D[i] == max(D.values()):
    print("Student with highest avg marks: ", i)
  if D[i] == min(D.values()):
    print("Student with lowest avg marks: ", i)

Enter the number of students: 3
Enter the name of the student: a
Enter the marks of the student in subject 1: 1
Enter the marks of the student in subject 2: 2
Enter the marks of the student in subject 3: 3
Enter the marks of the student in subject 4: 4
Enter the marks of the student in subject 5: 5
Enter the name of the student: b
Enter the marks of the student in subject 1: 2
Enter the marks of the student in subject 2: 3
Enter the marks of the student in subject 3: 4
Enter the marks of the student in subject 4: 5
Enter the marks of the student in subject 5: 6
Enter the name of the student: c
Enter the marks of the student in subject 1: 3
Enter the marks of the student in subject 2: 4
Enter the marks of the student in subject 3: 5
Enter the marks of the student in subject 4: 6
Enter the marks of the student in subject 5: 7
{'a': 3.0, 'b': 4.0, 'c': 5.0}
Student with lowest avg marks:  a
Student with highest avg marks:  c

In [20]:
import time as t
import random as r

start = t.time()
L = []
for i in range(0,10):
  L.append(r.randint(1,100))
print(L)
end = t.time()
print(end-start, "seconds")

[48, 18, 62, 54, 5, 3, 100, 16, 72, 69]
0.00025153160095214844 seconds

In [21]:
import time as t
import random as r

D = {}
n = int(input("Enter the number of lists: "))
for i in range(n):
  L = []
  size = int(input("Enter the size of the list: "))
  for j in range(size):
    L.append(r.randint(1,100))
    start = t.time()
    L.sort()
    end = t.time()
    D[size] = end - start

print(D)

Enter the number of lists: 5
Enter the size of the list: 5000
Enter the size of the list: 10000
Enter the size of the list: 15000
Enter the size of the list: 20000
Enter the size of the list: 25000
{5000: 1.6927719116210938e-05, 10000: 3.337860107421875e-05, 15000: 4.9114227294921875e-05, 20000: 6.532669067382812e-05, 25000: 8.344650268554688e-05}