<a href="https://colab.research.google.com/github/MiscMissLA/Mini-Project-01-Python-Assignment/blob/main/Assignment_Basics_Of_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Assignment- Basics Of Python Solutions

In [3]:
# ques 1
L = [11,12,13,14]
L.append(50)
L.append(60)
print(L)
print("----")


if (11 in L) == True:
  try:
    del L[0]
  except:
    print("Not Present.")
else:
  print("Not Present.")

if (13 in L) == True:
  try:
    del L[1]
  except:
    print("Not Present.")
else:
  print("Not Present.")
print(L)
print("----")


L.sort()
print(L)
print("----")


L.sort(reverse = True)
print(L)
print("----")


if (13 in L) == True:
  print("Present.")
else:
  print("Not Present.")
print("----")


for i in L:
  print(i, " count:  ", L.count(i))
print("----")


sum = 0
for i in L:
  sum+=i
print("sum is: ", sum)
print("----")


sum_odd = 0
sum_even = 0
for i in L:
  if (i%2!=0):
    sum_odd+=i
  else:
    sum_even += i
print("sum of odd numbers: ", sum_odd)
print("----")


print("sum of even numbers: ", sum_even)
print("----")


import math as m
flag = 0
sum_prime = 0
for i in L:
  for j in range(2, int(m.sqrt(i))+1):
    if (i%j == 0):
        print("Not Prime")
        flag = 1
        break
  if (flag == 0):
    sum_prime += i
    print("Prime ", i)
print("sum of prime numbers in list: ", sum_prime)
print("----")


L.clear()
print(L)
print("----")


del L
try:
  print(L)
except:
  print("Deleted.")
print("----")

[11, 12, 13, 14, 50, 60]
----
[12, 14, 50, 60]
----
[12, 14, 50, 60]
----
[60, 50, 14, 12]
----
Not Present.
----
60  count:   1
50  count:   1
14  count:   1
12  count:   1
----
sum is:  136
----
sum of odd numbers:  0
----
sum of even numbers:  136
----
Not Prime
Not Prime
Not Prime
Not Prime
sum of prime numbers in list:  0
----
[]
----
Deleted.
----

In [4]:
# ques 2
D = {1:5.6, 2:7.8, 3:6.6, 4:8.7, 5:7.7}

D[8] = 8.8
print(D)
print("----")


del D[2]
print(D)
print("----")


if (6 in D) == True:
  print("Present.")
else:
  print("Not Present.")
print("----")


count = 0
for i in D:
  count+=1
print("Count : ",count)

print("Count : ", len(D))
print("Count : ", len(D.keys()))
print("Count : ", len(D.values()))
print("----")

sum_values = 0
for i in D:
  sum_values += D[i]
print("Sum of values is: ", sum_values)
print("----")

if (3 in D):
  D[3] = 7.1
else:
  print("Not Present.")
print(D)
print("----")


D.clear()
print(D)
print("----")

del D
try:
  print(D)
except:
  print("Deleted.")
print("----")

{1: 5.6, 2: 7.8, 3: 6.6, 4: 8.7, 5: 7.7, 8: 8.8}
----
{1: 5.6, 3: 6.6, 4: 8.7, 5: 7.7, 8: 8.8}
----
Not Present.
----
Count :  5
Count :  5
Count :  5
Count :  5
----
Sum of values is:  37.4
----
{1: 5.6, 3: 7.1, 4: 8.7, 5: 7.7, 8: 8.8}
----
{}
----
Deleted.
----

In [5]:
# ques 3
S1 = {10, 20, 30, 40, 50, 60}
S2 = {40, 50, 60, 70, 80, 90}

print(S1)
print(S2)
print("----")

S1.add(55)
S1.add(66)
print(S1)
print("----")

S1.remove(10)
S1.remove(30)
print(S1)
print("----")

if (40 in S1):
  print("40 is Present.")
else:
  print("40 is Not Present.")
print("----")

print("Union of S1 and S2: ", S1.union(S2))
print("----")

print("Intersection of S1 and S2: ", S1.intersection(S2))
print("----")

print("Difference of S1 and S2: ", S1-S2, S1.difference(S2), " Symmetric Difference: ", S1.symmetric_difference(S2))
print("----")

{50, 20, 40, 10, 60, 30}
{80, 50, 70, 40, 90, 60}
----
{50, 66, 20, 55, 40, 10, 60, 30}
----
{50, 66, 20, 55, 40, 60}
----
40 is Present.
----
Union of S1 and S2:  {66, 70, 40, 80, 50, 20, 55, 90, 60}
----
Intersection of S1 and S2:  {40, 50, 60}
----
Difference of S1 and S2:  {66, 20, 55} {66, 20, 55}  Symmetric Difference:  {80, 66, 20, 70, 55, 90}
----

In [6]:
# ques 4
import string as s
import random as r
import math as m

for i in range(1,101):
  rs = r.sample(s.ascii_letters+s.digits+"!@#$%^&*", r.randint(6,8))
  rs = "".join(rs)
  print(i, rs)
print("----")


for i in range(600, 801):
  flag = 0
  for j in range(2, int(m.sqrt(i))+1):
    if (i%j == 0):
      flag = 1
      break
  if flag == 0:
    print(i , " is prime. ")
print("----")


for i in range(100, 1001):
  if (i%7 == 0 and i%9 == 0):
    print(i, "is divisible by 7 and 9.")
print("----")

1 f#!gKS
2 6kAWvG
3 AGXapN
4 Mq7dFlf
5 vhn^K!
6 0#nbps8^
7 @PIZU#
8 2zT87nq
9 KiGx!jYB
10 Y#BhfD
11 AdVH^8eU
12 &3z!o^
13 iP%wOvcj
14 1ShY6ZqE
15 vxsT60eU
16 #GwpJx1
17 XSfuypw0
18 Mlg4WeRd
19 ND3na&p@
20 %akIw8
21 *8ih69a
22 HL%v5k21
23 O5iw@p
24 ei!DxdlG
25 FVBuCL
26 !atKXR
27 bLD9gpMi
28 RmzQlk
29 w#^Kibt6
30 z%^5ac
31 fsYVJE
32 6#cjOhK
33 T$st@^3A
34 BiaxvC
35 S$5vCt0o
36 !yjpkWnO
37 1fY0A^
38 Zo5f3IL
39 Yn0tLe
40 OrNF5BfV
41 qGMsIk
42 Fsu5RMa$
43 5pRVu20M
44 dHfeSx
45 51m*SMQg
46 ORvBzN
47 lQXv!fq9
48 zLhfY&vd
49 X*$S#p1!
50 GUQrioY
51 1F*XYR9
52 qCoZ7iRy
53 !hbg6zYX
54 We@acd&U
55 mks6uSIZ
56 3myNfP6x
57 V6p8rMz^
58 4@7J!UV&
59 fy9LxkTw
60 vY9pg*
61 R&*rnSF
62 mrxtpL
63 v74MxlO
64 0OL2EkDu
65 feXb9TW
66 N0^Z@lX
67 lx4w@o*D
68 4k6IjVWL
69 Ls8Xk0C
70 B3heL#
71 8epsk#
72 Q0!dBAk
73 LVkfzB
74 8Hd7s%D
75 mM8cyQ
76 gN@lZsL
77 eZLVQo
78 lm!WT%
79 !VQcdjF
80 YmAG45qX
81 YJkbSa7V
82 2ZLtlk
83 D0Qo85Ii
84 YdPt4C
85 @yb*sWY
86 psIcDh&E
87 KTc6x#N
88 %Lb0uY
89 ^qQ62t
90 iBNPM4
91 D9xNd4b8
92 @bJc1^
93 ef5TlaO
94 dQ!1rW
95 @sb7KvlE
96 sDOxj8K
97 6iVqR#
98 h!RlbF
99 NnGgwO0K
100 &vIz8x
----
601  is prime.
607  is prime.
613  is prime.
617  is prime.
619  is prime.
631  is prime.
641  is prime.
643  is prime.
647  is prime.
653  is prime.
659  is prime.
661  is prime.
673  is prime.
677  is prime.
683  is prime.
691  is prime.
701  is prime.
709  is prime.
719  is prime.
727  is prime.
733  is prime.
739  is prime.
743  is prime.
751  is prime.
757  is prime.
761  is prime.
769  is prime.
773  is prime.
787  is prime.
797  is prime.
----
126 is divisible by 7 and 9.
189 is divisible by 7 and 9.
252 is divisible by 7 and 9.
315 is divisible by 7 and 9.
378 is divisible by 7 and 9.
441 is divisible by 7 and 9.
504 is divisible by 7 and 9.
567 is divisible by 7 and 9.
630 is divisible by 7 and 9.
693 is divisible by 7 and 9.
756 is divisible by 7 and 9.
819 is divisible by 7 and 9.
882 is divisible by 7 and 9.
945 is divisible by 7 and 9.
----

In [1]:
# ques 5
import random as r
L1 = []
L2 = []

print(L1)
print(L2)
print("----")

for i in range(1, 11):
  L1.append(r.randint(10,30))
  L2.append(r.randint(10,30))

print(L1)
print(L2)
print("----")

for i in L1:
  if i in L2:
    print(i, "is common in both L1 and L2.")
print("----")

L = []
for i in L1:
  if i not in L:
    L.append(i)
print("Unique elements in L1", L)

L.clear()

for i in L2:
  if i not in L:
    L.append(i)
print("Unique elements in L2", L)

L = set(L1)
print(L)

L = set(L2)
print(L)
print("----")

print("Minimum of L1", min(L1))
print("Minimum of L2", min(L2))
print("----")

print("Maximum of L1", max(L1))
print("Maximum of L2", max(L2))
print("----")

print("sum of L1", sum(L1))
print("sum of L2", sum(L2))
print("----")

[]
[]
----
[21, 12, 24, 28, 27, 12, 27, 19, 22, 30]
[29, 18, 28, 26, 21, 24, 23, 22, 12, 27]
----
21 is common in both L1 and L2.
12 is common in both L1 and L2.
24 is common in both L1 and L2.
28 is common in both L1 and L2.
27 is common in both L1 and L2.
12 is common in both L1 and L2.
27 is common in both L1 and L2.
22 is common in both L1 and L2.
----
Unique elements in L1 [21, 12, 24, 28, 27, 19, 22, 30]
Unique elements in L2 [29, 18, 28, 26, 21, 24, 23, 22, 12, 27]
{12, 19, 21, 22, 24, 27, 28, 30}
{12, 18, 21, 22, 23, 24, 26, 27, 28, 29}
----
Minimum of L1 12
Minimum of L2 12
----
Maximum of L1 30
Maximum of L2 29
----
sum of L1 222
sum of L2 230
----

In [2]:
# ques 6
import random as r
import math as m
L = []
for i in range(1,101):
  L.append(r.randint(100,900))

count_odd = 0
count_even = 0
count_prime = 0

for i in L:
  flag = 0
  if i%2 == 0:
    count_even += 1
    print(i, "is even.")
  else:
    count_odd += 1
    print(i, "is odd.")

  for j in range(2, int(m.sqrt(i))+1):
    if i%j == 0:
      flag = 1
      break

  if flag == 0:
    print(i, "is prime.")
    count_prime += 1
  else:
    print(i, "is not prime.")

print("odd count: ", count_odd)
print("even count: ", count_even)
print("prime count: ", count_prime)

827 is odd.
827 is prime.
450 is even.
450 is not prime.
100 is even.
100 is not prime.
634 is even.
634 is not prime.
711 is odd.
711 is not prime.
224 is even.
224 is not prime.
702 is even.
702 is not prime.
342 is even.
342 is not prime.
254 is even.
254 is not prime.
678 is even.
678 is not prime.
664 is even.
664 is not prime.
580 is even.
580 is not prime.
190 is even.
190 is not prime.
699 is odd.
699 is not prime.
534 is even.
534 is not prime.
412 is even.
412 is not prime.
425 is odd.
425 is not prime.
410 is even.
410 is not prime.
638 is even.
638 is not prime.
645 is odd.
645 is not prime.
306 is even.
306 is not prime.
594 is even.
594 is not prime.
475 is odd.
475 is not prime.
372 is even.
372 is not prime.
880 is even.
880 is not prime.
874 is even.
874 is not prime.
189 is odd.
189 is not prime.
515 is odd.
515 is not prime.
873 is odd.
873 is not prime.
108 is even.
108 is not prime.
786 is even.
786 is not prime.
147 is odd.
147 is not prime.
810 is even.
810 is not prime.
802 is even.
802 is not prime.
355 is odd.
355 is not prime.
201 is odd.
201 is not prime.
700 is even.
700 is not prime.
390 is even.
390 is not prime.
101 is odd.
101 is prime.
539 is odd.
539 is not prime.
270 is even.
270 is not prime.
302 is even.
302 is not prime.
884 is even.
884 is not prime.
243 is odd.
243 is not prime.
777 is odd.
777 is not prime.
226 is even.
226 is not prime.
679 is odd.
679 is not prime.
511 is odd.
511 is not prime.
369 is odd.
369 is not prime.
840 is even.
840 is not prime.
779 is odd.
779 is not prime.
822 is even.
822 is not prime.
334 is even.
334 is not prime.
524 is even.
524 is not prime.
854 is even.
854 is not prime.
731 is odd.
731 is not prime.
262 is even.
262 is not prime.
697 is odd.
697 is not prime.
311 is odd.
311 is prime.
425 is odd.
425 is not prime.
440 is even.
440 is not prime.
123 is odd.
123 is not prime.
132 is even.
132 is not prime.
111 is odd.
111 is not prime.
470 is even.
470 is not prime.
255 is odd.
255 is not prime.
860 is even.
860 is not prime.
470 is even.
470 is not prime.
571 is odd.
571 is prime.
683 is odd.
683 is prime.
640 is even.
640 is not prime.
356 is even.
356 is not prime.
886 is even.
886 is not prime.
767 is odd.
767 is not prime.
855 is odd.
855 is not prime.
782 is even.
782 is not prime.
511 is odd.
511 is not prime.
278 is even.
278 is not prime.
210 is even.
210 is not prime.
753 is odd.
753 is not prime.
436 is even.
436 is not prime.
822 is even.
822 is not prime.
415 is odd.
415 is not prime.
619 is odd.
619 is prime.
628 is even.
628 is not prime.
246 is even.
246 is not prime.
762 is even.
762 is not prime.
715 is odd.
715 is not prime.
541 is odd.
541 is prime.
480 is even.
480 is not prime.
471 is odd.
471 is not prime.
345 is odd.
345 is not prime.
222 is even.
222 is not prime.
431 is odd.
431 is prime.
626 is even.
626 is not prime.
598 is even.
598 is not prime.
497 is odd.
497 is not prime.
891 is odd.
891 is not prime.
260 is even.
260 is not prime.
174 is even.
174 is not prime.
odd count:  42
even count:  58
prime count:  8

In [7]:
# ques 7
D = {1:"One", 2: "Two", 3: "Three", 4:"Four", 5:"Five"}
fp = open("file1.txt", "w")
for i in D:
  fp.write(str(i)+","+str(D[i])+"\n")
fp.close()

In [8]:
# ques 8
L = ["One", "Two", "Three", "Four", "Five"]
fp = open("file1.txt", "w")
for i in L:
  fp.write(i+","+str(len(i))+"\n")
fp.close()

In [9]:
# ques 9
import string as s
import random as r

fp = open("file1.txt", "w")

for i in range(1, 101):
  rs = r.sample(s.ascii_letters, r.randint(10,15))
  rs = "".join(rs)
  fp.write(rs+"\n")

fp.close()

In [10]:
# ques 10
import math as m
fp = open("file1.txt", "w")
for i in range(600, 801):
  flag = 0
  for j in range(2, int(m.sqrt(i))+1):
    if (i%j == 0):
      flag = 1
      break
  if flag == 0:
    fp.write(str(i)+"\n")

fp.close()

In [11]:
# ques 11
import time as t
import random as r

start = t.time()
L = []
for i in range(0,10):
  L.append(r.randint(1,100))
print(L)
end = t.time()
print(end-start, "seconds")

[20, 61, 25, 66, 56, 69, 43, 98, 30, 44]
0.0004124641418457031 seconds

In [12]:
# ques 12
import time as t
import random as r

D = {}
n = int(input("Enter the number of lists: "))
for i in range(n):
  L = []
  size = int(input("Enter the size of the list: "))
  for j in range(size):
    L.append(r.randint(1,100))
    start = t.time()
    L.sort()
    end = t.time()
    D[size] = end - start

print(D)

Enter the number of lists: 5
Enter the size of the list: 5000
Enter the size of the list: 10000
Enter the size of the list: 15000
Enter the size of the list: 20000
Enter the size of the list: 25000
{5000: 1.6689300537109375e-05, 10000: 3.2901763916015625e-05, 15000: 4.935264587402344e-05, 20000: 6.699562072753906e-05, 25000: 0.0001609325408935547}

In [13]:
# ques 13
n = int(input("Enter the number of students: "))
D = {}
for i in range(0, n):
  name = input("Enter the name of the student: ")
  sum = 0
  for j in range(0,5):
    s = "Enter the marks of the student in subject %d: " %(j+1)
    marks = int(input(s))
    sum += marks
  avg = sum/5;
  D[name] = avg
print(D)

for i in D:
  if D[i] == max(D.values()):
    print("Student with highest avg marks: ", i)
  if D[i] == min(D.values()):
    print("Student with lowest avg marks: ", i)

Enter the number of students: 3
Enter the name of the student: a
Enter the marks of the student in subject 1: 78
Enter the marks of the student in subject 2: 89
Enter the marks of the student in subject 3: 56
Enter the marks of the student in subject 4: 98
Enter the marks of the student in subject 5: 55
Enter the name of the student: b
Enter the marks of the student in subject 1: 77
Enter the marks of the student in subject 2: 98
Enter the marks of the student in subject 3: 90
Enter the marks of the student in subject 4: 78
Enter the marks of the student in subject 5: 66
Enter the name of the student: c
Enter the marks of the student in subject 1: 89
Enter the marks of the student in subject 2: 67
Enter the marks of the student in subject 3: 56
Enter the marks of the student in subject 4: 76
Enter the marks of the student in subject 5: 72
{'a': 75.2, 'b': 81.8, 'c': 72.0}
Student with highest avg marks:  b
Student with lowest avg marks:  c